import React, { useState } from 'react';
import { 
  Gavel, 
  CheckCircle2, 
  XCircle, 
  AlertCircle, 
  Copy, 
  Check, 
  PlusCircle, 
  Download, 
  Filter, 
  Search, 
  ShieldCheck, 
  AlertTriangle, 
  HelpCircle, 
  FileText, 
  Scale, 
  ArrowLeft,
  Share2,
  Sparkles
} from 'lucide-react';
import { DebateSession, DebateTurn, VerdictType } from '../types/debate';
import { ToolCallDisplay } from './ToolCallDisplay';

interface VerdictViewProps {
  session: DebateSession;
  onStartNewDebate: () => void;
  onBackToDebate: () => void;
  onRerunDebate?: (session: DebateSession) => void;
}

export const VerdictView: React.FC<VerdictViewProps> = ({
  session,
  onStartNewDebate,
  onBackToDebate,
  onRerunDebate,
}) => {
  const [copied, setCopied] = useState(false);
  const [filterRole, setFilterRole] = useState<'all' | 'pro' | 'con' | 'moderator'>('all');
  const [searchQuery, setSearchQuery] = useState('');

  const verdict = session.verdict;

  if (!verdict) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-16 text-center">
        <div className="w-12 h-12 rounded-full bg-slate-800 flex items-center justify-center mx-auto mb-3 text-slate-400">
          <Gavel className="w-6 h-6 text-indigo-400" />
        </div>
        <h2 className="text-xl font-bold text-white mb-2">Verdict Pending</h2>
        <p className="text-sm text-slate-400 mb-6">
          This debate is still in deliberation and has not received a final judgment.
        </p>
        <button
          onClick={onBackToDebate}
          className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold"
        >
          Return to Active Debate
        </button>
      </div>
    );
  }

  // Format full Markdown including question, transcript, and verdict for clipboard
  const handleCopyMarkdown = () => {
    const formattedTranscript = session.transcript.map(t => {
      const roleName = t.agentName || (t.agentRole === 'pro' ? 'Pro Agent' : t.agentRole === 'con' ? 'Con Agent' : t.agentRole === 'moderator' ? 'Moderator' : 'Judge');
      const points = t.keyPoints && t.keyPoints.length > 0 ? `\nKey Points:\n${t.keyPoints.map(p => `  * ${p}`).join('\n')}` : '';
      
      let toolDetails = '';
      const calls = [];
      if (t.toolCall) calls.push(t.toolCall);
      if (t.toolCalls) calls.push(...t.toolCalls);
      if (calls.length > 0) {
        toolDetails = `\n\nTool Executions:\n` + calls.map(c => {
          let s = `  * Tool: ${c.name} [Status: ${c.status.toUpperCase()}]`;
          if (c.query) s += ` - Query: "${c.query}"`;
          if (c.error) s += ` - Error: ${c.error}`;
          if (c.sources && c.sources.length > 0) {
            s += `\n    Sources:\n` + c.sources.map(src => `      - ${src.title || src.url || 'Source'}${src.url ? ` (${src.url})` : ''}`).join('\n');
          }
          return s;
        }).join('\n');
      }

      return `### Round ${t.round} · ${roleName}: ${t.title}\n${t.content}${points}${toolDetails}\n`;
    }).join('\n---\n\n');

    const confidenceLine = verdict.confidence !== undefined && verdict.confidence !== null 
      ? ` (Confidence: ${verdict.confidence}%)` 
      : '';

    const md = `# DebateDesk Multi-Agent Decision Audit
**Question**: ${session.question}
${session.backgroundContext ? `**Context**: ${session.backgroundContext}\n` : ''}${session.decisionCriteria ? `**Evaluation Criteria**: ${session.decisionCriteria}\n` : ''}**Date**: ${new Date(session.createdAt).toLocaleDateString()}
**Final Verdict**: ${verdict.verdict.toUpperCase()}${confidenceLine}

## Executive Summary
${verdict.summary}

## Deciding Factors
${verdict.decidingFactors.map(f => `- ${f}`).join('\n')}

## Critical Risks & Vulnerabilities
${verdict.risks.map(r => `- ${r}`).join('\n')}

## Actionable Recommendations & Conditions
${verdict.actionableRecommendations.map(a => `- ${a}`).join('\n')}

## Detailed Judge Reasoning Synthesis
${verdict.reasoning}

---

## Complete Multi-Agent Transcript (${session.totalRounds} Rounds, ${session.transcript.length} Turns)

${formattedTranscript}

---
*Generated by DebateDesk Multi-Agent Decision Engine (${session.isDemo ? 'Demo Mode - Simulated Deliberation' : 'Real Backend Deliberation'})*
`;

    navigator.clipboard.writeText(md).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const handleDownloadJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(session, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `debatedesk-${session.id}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  // Filter transcript
  const filteredTranscript = session.transcript.filter((turn) => {
    const matchesRole = filterRole === 'all' || turn.agentRole === filterRole;
    const matchesSearch = searchQuery === '' || 
      turn.content.toLowerCase().includes(searchQuery.toLowerCase()) ||
      turn.title.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesRole && matchesSearch;
  });

  // Verdict theme variables
  const isYes = verdict.verdict === 'Yes';
  const isNo = verdict.verdict === 'No';
  const isConditional = verdict.verdict === 'Conditional';

  const verdictBgClass = isYes 
    ? 'bg-emerald-500/10 border-emerald-500/40 text-emerald-400'
    : isNo
    ? 'bg-rose-500/10 border-rose-500/40 text-rose-400'
    : 'bg-amber-500/10 border-amber-500/40 text-amber-400';

  const verdictIcon = isYes 
    ? <CheckCircle2 className="w-8 h-8 text-emerald-400 shrink-0" />
    : isNo
    ? <XCircle className="w-8 h-8 text-rose-400 shrink-0" />
    : <AlertCircle className="w-8 h-8 text-amber-400 shrink-0" />;

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-10">
      
      {/* Top Demo Notice & Action Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
        <button
          onClick={onBackToDebate}
          className="inline-flex items-center gap-1.5 text-xs text-slate-300 hover:text-white transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 rounded-lg px-2 py-1.5 cursor-pointer font-medium"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Live Stream</span>
        </button>

        <div className="flex flex-wrap items-center gap-2">
          {/* DEMO MODE Pill */}
          <div 
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-amber-500/10 border border-amber-500/30 text-amber-300 text-xs font-semibold select-none"
            aria-label="Simulation state: Demo Mode"
          >
            <span className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse" aria-hidden="true" />
            <span>DEMO MODE · Simulated Deliberation</span>
          </div>

          <button
            onClick={handleCopyMarkdown}
            aria-live="polite"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer shadow-sm"
            title="Copy full decision record to clipboard"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
            <span>{copied ? 'Copied Full Report!' : 'Copy Results'}</span>
          </button>

          <button
            onClick={handleDownloadJSON}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer shadow-sm"
            title="Download complete session data as JSON"
          >
            <Download className="w-3.5 h-3.5 text-slate-400" />
            <span className="hidden sm:inline">Export JSON</span>
          </button>

          {onRerunDebate && (
            <button
              onClick={() => onRerunDebate(session)}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-slate-800 hover:bg-slate-700 text-indigo-300 text-xs font-semibold border border-indigo-500/40 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer shadow-sm"
              title="Adjust rounds or parameters and run again"
            >
              <Sparkles className="w-3.5 h-3.5 text-indigo-400" />
              <span>Re-run / Adjust</span>
            </button>
          )}

          <button
            onClick={onStartNewDebate}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-md bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 text-white text-xs font-semibold shadow-sm shadow-indigo-600/30 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer"
          >
            <PlusCircle className="w-3.5 h-3.5" />
            <span>New Debate</span>
          </button>
        </div>
      </div>

      {/* Decision Question Card */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 sm:p-6 mb-6 shadow-md">
        <div className="flex flex-wrap items-center gap-2 text-xs text-slate-400 mb-2">
          <Scale className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
          <span className="font-semibold text-slate-300">Decision Under Audit</span>
          <span className="text-slate-600">·</span>
          <span className="text-slate-300">{session.totalRounds} Rounds Evaluated</span>
          <span className="text-slate-600">·</span>
          <span className="font-mono text-[11px] text-slate-400">{new Date(session.createdAt).toLocaleDateString()}</span>
        </div>
        <h1 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight leading-snug">
          {session.question}
        </h1>
        {session.backgroundContext && (
          <p className="mt-3 text-xs sm:text-sm text-slate-200 border-t border-slate-800/80 pt-2.5 leading-relaxed">
            <strong className="text-white font-semibold">Context & Constraints: </strong>
            {session.backgroundContext}
          </p>
        )}
        {session.decisionCriteria && (
          <p className="mt-2 text-xs sm:text-sm text-slate-200 leading-relaxed">
            <strong className="text-white font-semibold">Evaluation Criteria: </strong>
            {session.decisionCriteria}
          </p>
        )}
      </div>

      {/* Judge Verdict Hero Card */}
      <div className="bg-slate-900/95 border border-slate-800 rounded-xl p-6 sm:p-8 mb-8 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 pb-6 border-b border-slate-800">
          
          {/* Verdict Badge */}
          <div className="flex items-center gap-4">
            <div className={`p-3.5 rounded-2xl border ${verdictBgClass} shadow-md`}>
              {verdictIcon}
            </div>
            <div>
              <div className="text-xs uppercase tracking-wider font-bold text-slate-400 mb-1">
                Judge Agent Arbitration
              </div>
              <div className="text-3xl sm:text-4xl font-black tracking-tight text-white flex flex-wrap items-center gap-3">
                <span>{verdict.verdict.toUpperCase()}</span>
                {isConditional && (
                  <span className="text-xs font-semibold text-amber-300 bg-amber-500/15 border border-amber-500/40 px-2.5 py-1 rounded-md">
                    Subject to Piloting & Constraints
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Confidence Score Metric (Rendered only when supplied by demo result) */}
          {verdict.confidence !== undefined && verdict.confidence !== null && (
            <div className="sm:text-right bg-slate-950/80 p-4 rounded-xl border border-slate-800 min-w-[210px] shadow-sm">
              <div className="flex items-center justify-between sm:justify-end gap-2 text-xs text-slate-300 mb-1">
                <span className="font-semibold text-slate-200">Confidence Score</span>
                <span className="text-[10px] uppercase font-mono px-1.5 py-0.5 rounded bg-indigo-950/90 text-indigo-300 border border-indigo-800/50 font-bold">
                  {verdict.confidence >= 85 ? 'High Certainty' : verdict.confidence >= 75 ? 'Substantial' : 'Moderate'}
                </span>
              </div>
              <div className="text-3xl font-extrabold font-mono tabular-nums text-white">
                {verdict.confidence}%
              </div>
              <div className="w-full bg-slate-800 h-2 rounded-full mt-2 overflow-hidden">
                <div 
                  className="bg-gradient-to-r from-indigo-500 to-indigo-400 h-full rounded-full transition-all duration-500" 
                  style={{ width: `${verdict.confidence}%` }} 
                />
              </div>
              {verdict.voteBreakdown && (
                <div className="mt-2.5 pt-2 border-t border-slate-800/80 flex items-center justify-between text-[11px] font-mono text-slate-400">
                  <span className="text-emerald-400 font-semibold">Pro {verdict.voteBreakdown.proStrength}%</span>
                  <span className="text-slate-600">vs</span>
                  <span className="text-rose-400 font-semibold">Con {verdict.voteBreakdown.conStrength}%</span>
                </div>
              )}
            </div>
          )}

        </div>

        {/* Executive Summary */}
        <div className="py-5 border-b border-slate-800/80">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2">
            Executive Summary
          </h2>
          <p className="text-base sm:text-lg text-slate-100 leading-relaxed font-semibold">
            "{verdict.summary}"
          </p>
        </div>


        {/* Deciding Factors & Risks Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-6">
          
          {/* Deciding Factors */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-sm font-bold text-emerald-400">
              <CheckCircle2 className="w-4 h-4 shrink-0" />
              <span>Deciding Factors & Weighted Rationales</span>
            </div>
            <ul className="space-y-2.5 text-xs text-slate-200" aria-label="Deciding Factors">
              {verdict.decidingFactors.map((factor, idx) => (
                <li key={idx} className="flex items-start gap-2.5 bg-slate-950/70 p-3 rounded-xl border border-slate-800/80 shadow-sm leading-relaxed">
                  <span className="w-5 h-5 rounded-full bg-emerald-500/20 text-emerald-400 font-bold font-mono text-xs flex items-center justify-center shrink-0 mt-0.5">{idx + 1}</span>
                  <span className="text-slate-200">{factor}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Risks & Vulnerabilities */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-sm font-bold text-rose-400">
              <AlertTriangle className="w-4 h-4 shrink-0" />
              <span>Identified Risks & Vulnerabilities</span>
            </div>
            <ul className="space-y-2.5 text-xs text-slate-200" aria-label="Identified Risks">
              {verdict.risks.map((risk, idx) => (
                <li key={idx} className="flex items-start gap-2.5 bg-slate-950/70 p-3 rounded-xl border border-slate-800/80 shadow-sm leading-relaxed">
                  <span className="w-5 h-5 rounded-full bg-rose-500/20 text-rose-400 font-bold font-mono text-xs flex items-center justify-center shrink-0 mt-0.5">{idx + 1}</span>
                  <span className="text-slate-200">{risk}</span>
                </li>
              ))}
            </ul>
          </div>

        </div>

        {/* Actionable Recommendations / Conditions */}
        {verdict.actionableRecommendations && verdict.actionableRecommendations.length > 0 && (
          <div className="mt-6 pt-6 border-t border-slate-800">
            <div className="flex items-center gap-2 text-sm font-bold text-indigo-300 mb-3">
              <Sparkles className="w-4 h-4 text-indigo-400 shrink-0" />
              <span>Recommended Next Steps & Governance Gates</span>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {verdict.actionableRecommendations.map((rec, idx) => (
                <div key={idx} className="p-3.5 rounded-xl bg-indigo-950/30 border border-indigo-500/25 text-xs text-slate-200 flex items-start gap-2.5 leading-relaxed">
                  <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mt-2 shrink-0" />
                  <span>{rec}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Full Judge Reasoning Text */}
        <div className="mt-6 pt-6 border-t border-slate-800">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2">
            Detailed Judge Reasoning Synthesis
          </h3>
          <p className="text-xs sm:text-sm text-slate-200 leading-relaxed bg-slate-950/60 p-4 sm:p-5 rounded-xl border border-slate-800/90 font-normal">
            {verdict.reasoning}
          </p>
        </div>

      </div>

      {/* Full Transcript Section with Role Filter */}
      <div className="bg-slate-900/95 border border-slate-800 rounded-xl p-5 sm:p-6 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-slate-800 mb-6">
          <div>
            <h2 className="text-base font-bold text-white tracking-tight">
              Complete Multi-Agent Transcript
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Chronological record of all {session.transcript.length} turns across {session.totalRounds} rounds
            </p>
          </div>

          {/* Filter & Search Bar */}
          <div className="flex flex-wrap items-center gap-2">
            <div className="relative">
              <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search transcript..."
                aria-label="Search transcript"
                className="pl-8 pr-3 py-1.5 text-xs bg-slate-950 border border-slate-800 rounded-lg text-slate-100 placeholder-slate-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:border-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 transition-colors"
              />
            </div>

            {/* Segmented Filter */}
            <div className="flex items-center gap-1 p-0.5 bg-slate-950 rounded-lg border border-slate-800 text-xs" role="tablist" aria-label="Filter transcript by agent">
              <button
                role="tab"
                aria-selected={filterRole === 'all'}
                onClick={() => setFilterRole('all')}
                className={`px-2.5 py-1 rounded-md font-semibold transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer ${
                  filterRole === 'all' ? 'bg-indigo-600 text-white shadow-sm' : 'text-slate-300 hover:text-white'
                }`}
              >
                All
              </button>
              <button
                role="tab"
                aria-selected={filterRole === 'pro'}
                onClick={() => setFilterRole('pro')}
                className={`px-2.5 py-1 rounded-md font-semibold transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer ${
                  filterRole === 'pro' ? 'bg-emerald-600 text-white shadow-sm' : 'text-slate-300 hover:text-white'
                }`}
              >
                Pro
              </button>
              <button
                role="tab"
                aria-selected={filterRole === 'con'}
                onClick={() => setFilterRole('con')}
                className={`px-2.5 py-1 rounded-md font-semibold transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer ${
                  filterRole === 'con' ? 'bg-rose-600 text-white shadow-sm' : 'text-slate-300 hover:text-white'
                }`}
              >
                Con
              </button>
              <button
                role="tab"
                aria-selected={filterRole === 'moderator'}
                onClick={() => setFilterRole('moderator')}
                className={`px-2.5 py-1 rounded-md font-semibold transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer ${
                  filterRole === 'moderator' ? 'bg-cyan-600 text-white shadow-sm' : 'text-slate-300 hover:text-white'
                }`}
              >
                Moderator
              </button>
            </div>
          </div>
        </div>

        {/* Filtered Transcript List */}
        <div className="space-y-4">
          {filteredTranscript.length === 0 ? (
            <div className="p-8 text-center text-xs text-slate-300 bg-slate-950/40 rounded-xl border border-slate-800">
              No turns match the selected filter or search query.
            </div>
          ) : (
            filteredTranscript.map((turn, idx) => (
              <div 
                key={turn.id || idx}
                className={`p-4 sm:p-5 rounded-xl border text-left transition-all ${
                  turn.agentRole === 'pro'
                    ? 'bg-slate-950/70 border-l-4 border-l-emerald-500 border-slate-800/90'
                    : turn.agentRole === 'con'
                    ? 'bg-slate-950/70 border-l-4 border-l-rose-500 border-slate-800/90'
                    : turn.kind === 'moderator_question'
                    ? 'bg-slate-950/70 border-l-4 border-l-cyan-400 border-slate-800/90'
                    : 'bg-slate-950/70 border-l-4 border-l-indigo-400 border-slate-800/90'
                }`}
              >
                <div className="flex flex-wrap items-center justify-between gap-2 text-xs mb-2">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-slate-100">
                      {turn.agentName}
                    </span>
                    <span className="text-slate-600">·</span>
                    <span className="text-[11px] text-slate-400 font-mono">{turn.timestamp}</span>
                  </div>
                  <span className="text-[10px] uppercase font-mono tracking-wider text-slate-300 bg-slate-900 px-2 py-0.5 rounded border border-slate-800 font-medium">
                    {turn.kind.replace('_', ' ')}
                  </span>
                </div>

                <h4 className="text-sm sm:text-base font-bold text-white mb-1.5 leading-snug">{turn.title}</h4>
                <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">{turn.content}</p>

                {turn.keyPoints && turn.keyPoints.length > 0 && (
                  <div className="mt-3 pt-2.5 border-t border-slate-800/80 space-y-1.5">
                    {turn.keyPoints.map((kp, kIdx) => (
                      <div key={kIdx} className="flex items-start gap-2 text-xs sm:text-sm text-slate-200 leading-relaxed">
                        <span className="w-1.5 h-1.5 rounded-full bg-slate-400 mt-2 shrink-0" aria-hidden="true" />
                        <span>{kp}</span>
                      </div>
                    ))}
                  </div>
                )}

                <ToolCallDisplay toolCall={turn.toolCall} toolCalls={turn.toolCalls} />
              </div>
            ))
          )}
        </div>

        {/* Footer Actions */}
        <div className="mt-8 pt-5 border-t border-slate-800 flex flex-wrap items-center justify-between gap-4">
          <div className="text-xs text-slate-400 font-medium">
            Debate Desk Decision Framework · Multi-Agent Adversarial Consensus
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleCopyMarkdown}
              className="text-xs text-indigo-400 hover:text-indigo-300 font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 rounded px-1.5 py-1 cursor-pointer"
            >
              Copy Full Transcript & Verdict
            </button>
            <button
              onClick={onStartNewDebate}
              className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 text-white text-xs font-semibold shadow-md shadow-indigo-600/20 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 cursor-pointer"
            >
              Start Another Debate
            </button>
          </div>
        </div>

      </div>

    </div>
  );
};
